# -*- coding: utf-8 -*-
"""Atividade_EaD_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o6iLNcIaVSuzi6jlJrhqcEYQ-eGqIkSz
"""

#Questão 2 e 3) Como utilizei o ambiente do Google Colab, a função quit() não funciona. Portanto,
#foi necessário importar a biblioteca sys e utilizar o método exit() para obter o mesmo resultado 
#da função quit(). Isso ocorre porque os dois métodos lançam uma exceção que finaliza o ambiente
#de execução.

import sys

# Calculadora
print('Entre com o primeiro número: ')
num1 = input()
num1_original = num1
if(num1.replace(".", "").isdigit()):
  num1 = float(num1_original)
else:
  print("Entre somente com números.")
  sys.exit()
print('Entre com o segundo número: ')
num2 = input()
num2_original = num2
if(num2.replace(".", "").isdigit()):
  num2 = float(num2_original)
else:
  print("Entre somente com números.")
  sys.exit()
print('Entre com a operação (+ - * /): ')
oper = input()
resultado = 0
if oper == '+':
 resultado = num1 + num2
elif oper == '-':
 resultado = num1 - num2
elif oper == '*':
 resultado = num1 * num2
elif oper == '/':
 resultado = num1 / num2
else:
 print('Operação não válida')
 sys.exit()
print(str(num1) + ' ' + oper + ' ' + str(num2) + ' = ' + str(round(resultado,2)))

#Questão 4) A função float() serve para transformar o input em um dado do tipo float. 
#Isso é necessário neste programa, pois, caso contrário, números com ponto flutuante (decimais) 
#não seriam aceitos, causando o lançamento de uma exceção durante a execução.

#Questão 5) A função quit() serve para lançar uma exceção que finaliza o ambiente de execução.