# -*- coding: utf-8 -*-
"""Atividades_EaD_04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qzXUCZD09yV9YLzDn6DlVmNOojXngUqU
"""

import numpy as np
def primeiro_digito_cpf(cpf):
  pesos = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2], dtype=int)

  array_cpf = np.array([cpf[0], cpf[1], cpf[2], cpf[3], cpf[4], cpf[5], cpf[6], cpf[7], cpf[8]], dtype=int)

  soma = 0
  for i in range(0, 9, 1):
    soma = soma + (pesos[i] * array_cpf[i])

  resto = soma%11
  primeiro_digito = 0

  if(resto >= 2):
    primeiro_digito = 11 - resto 

  return primeiro_digito

def segundo_digito_cpf(cpf, primeiro_digito):
  pesos = np.array([11, 10, 9, 8, 7, 6, 5, 4, 3, 2], dtype=int)

  array_cpf = np.array([cpf[0], cpf[1], cpf[2], cpf[3], cpf[4], cpf[5], cpf[6], cpf[7], cpf[8], primeiro_digito], dtype=int)
  
  soma = 0
  for i in range(0, 10, 1):
    soma = soma + (pesos[i] * array_cpf[i])

  resto = soma%11

  segundo_digito = 0

  if(resto >= 2):
    segundo_digito = 11 - resto

  return segundo_digito

def calcula_digitos_verificadores():
  print("Entre com os nove primeiros dígitos do seu cpf:")
  cpf = input()
  primeiro_digito = primeiro_digito_cpf(cpf)
  segundo_digito = segundo_digito_cpf(cpf, primeiro_digito)
  cpf = str(cpf) + str(primeiro_digito) + str(segundo_digito)
  print(f'Dígitos verificadores do seu cpf:{primeiro_digito}{segundo_digito}')
  print(f'Seu cpf:{cpf}')

calcula_digitos_verificadores()

